---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install -g phantomjs
  - npm install
  - bower install

script:
  - grunt test
  - ember test
